# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af93f8d411449fb2c27fce786d65e661d8253613a1ccde4c0f7b4cc0dd362ec067cc4d792e48a81b6f98891dd84263630bb8785d15f7986ca4e9b7599841c04

test:
  secret_key_base: 31d3bb98f15a581aa9feb108c9c41be2082b71711024f0b6c7409513b41e1c886a255920b3487fcc05a49aef0673f86c36e1d2d67ddca31bd2a9eaa3b0dd2a58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
